engines:
  tslint:
    enabled: true
    channel: beta
    checks:
      ban-types:
        enabled: false
      no-empty:
        enabled: false
      interface-name:
        enabled: false
      arrow-return-shorthand:
        enabled: false
exclude_paths:
  - "**.php"
  - "Docker/"
ratings:
   paths:
    - "admin/**/*"
