sudo: required

language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer install
  - cp .env.example .env

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter

addons:
    code_climate:
        repo_token: b6d9309226c2150e2e642db85ed04195941d29bedaa4f10f0c6d0e2b1f2b09e8

