sudo: required

services:
  - docker

language: php

php:
  - 7.0

before_script:
  - sudo /etc/init.d/mysql stop
  - docker-compose up -d
  - composer docker-update
  - cp .env.example .env

script:
  - docker exec -it remarker_web_1 php -v
  - composer coverage-clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml
