version: "2"
services:
  # Web node
  web:
    build: ./Docker/web/
    volumes:
      - ./:/var/www
    ports:
      - 8080:80
    links:
      - db

  # Database
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=remarker
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local